SELECT TOP (1000) [Username]
      ,[User_ID]
      ,[ReportRun_ID]
      ,[Dated]
      ,[Action]
      ,[IP_Address]
      ,[A_NightAudit_ID]
      ,[Browser_Used]
  FROM [dbo].[ac_qryLogs_A_NightAudit]