SELECT TOP (1000) [ID]
      ,[Summary_Group]
      ,[Summary_Type]
      ,[FormatCode]
      ,[Day1]
      ,[Day2]
      ,[Day3]
      ,[Day4]
      ,[Day5]
      ,[Day6]
      ,[Day7]
      ,[Total]
      ,[BatchNo]
      ,[AuditDate]
      ,[Hotel_ID]
  FROM [dmr].[tbl_Final_Past7Days]