SELECT TOP (1000) [Username]
      ,[User_ID]
      ,[NASReport_ID]
      ,[Dated]
      ,[Action]
      ,[IP_Address]
      ,[A_NAS_ID]
      ,[Browser_Used]
      ,[FullName]
  FROM [dbo].[ac_qryLogs_A_NAS]